# Generated by Django 4.1.7 on 2023-03-11 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organize", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Run",
            fields=[
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, verbose_name="order"
                    ),
                ),
                ("uuid", models.UUIDField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("order",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Scoresheet",
            fields=[
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, verbose_name="order"
                    ),
                ),
                ("uuid", models.UUIDField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("score", models.DecimalField(decimal_places=2, max_digits=8)),
                ("arrow_score", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organize.group"
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organize.registration",
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ScoreItem",
            fields=[
                ("uuid", models.UUIDField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("target", "Target"),
                            ("time", "Time"),
                            ("bonus", "Bonus/Penalty"),
                            ("incident", "Incident"),
                        ],
                        max_length=16,
                    ),
                ),
                ("value", models.JSONField()),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="judge.run"
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_permissions": [],
            },
        ),
        migrations.AddField(
            model_name="run",
            name="scoresheet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="judge.scoresheet"
            ),
        ),
    ]
