# Generated by Django 4.1.7 on 2023-03-11 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Discipline",
            fields=[
                ("uuid", models.UUIDField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
            ],
            options={
                "abstract": False,
                "default_permissions": [],
            },
        ),
        migrations.CreateModel(
            name="RuleSet",
            fields=[
                ("uuid", models.UUIDField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
                ("ihaa_official", models.BooleanField(default=False)),
                ("interface_code", models.CharField(blank=True, max_length=128)),
                ("description", models.TextField(blank=True)),
                ("rules", models.JSONField()),
                (
                    "discipline",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="rules.discipline",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_permissions": [],
            },
        ),
    ]
